/* Imported from dbalatoni13/nfsmw @ 9ca26bc1 (src/Speed/Indep/Libs/snd/9/source/library/cmn/sndenum.h). EA SND audio library (rwaudiocore), matched against NFS Most Wanted GC; CC0. */
#ifndef SND_CMN_ENUM_H
#define SND_CMN_ENUM_H

// TODO: Where does this stuff go??

namespace Snd {

enum Channel {
    CHANNEL_ALL = -1,
    CHANNEL_CENTER = 0,
    CHANNEL_LEFT = 1,
    CHANNEL_RIGHT = 2,
    CHANNEL_LEFTSURROUND = 3,
    CHANNEL_RIGHTSURROUND = 4,
    CHANNEL_LFE = 5,
    CHANNEL_MAX = 6,
};

enum Status {
    STATUS_PLAYING = 0,
    STATUS_PAUSED = 1,
    STATUS_STOPPED = 2,
    STATUS_OVER = 3,
};

enum OutputMode {
    OUTPUTMODE_MONO = 0,
    OUTPUTMODE_STEREO = 1,
    OUTPUTMODE_4POINT0 = 2,
    OUTPUTMODE_5POINT1 = 3,
    OUTPUTMODE_DTS4POINT0 = 4,
    OUTPUTMODE_DTS5POINT1 = 5,
    OUTPUTMODE_DD5POINT1 = 6,
    OUTPUTMODE_PROLOGIC = 7,
    OUTPUTMODE_PROLOGIC2 = 8,
    OUTPUTMODE_MAX = 9,
};

enum CompatibilityMode {
    COMPATIBILITYMODE_LOW = -1,
    COMPATIBILITYMODE_MED = 0,
    COMPATIBILITYMODE_HIGH = 1,
    COMPATIBILITYMODE_HIGHEST = 2,
};

enum Device {
    DEVICE_MAIN = 0,
    DEVICE_IOP = 1,
    DEVICE_HARDWARE = 2,
    DEVICE_HARDWARE3D = 3,
    DEVICE_MAX = 4,
};

enum FileFormat {
    FILEFORMAT_MP3 = 0,
    FILEFORMAT_AIFF = 1,
    FILEFORMAT_WAVE = 2,
    FILEFORMAT_WMA = 3,
    FILEFORMAT_ATRAC3 = 4,
};

enum FxPreset {
    FXPRESET_REVERB_GENERIC = 100,
    FXPRESET_REVERB_PADDEDCELL = 110,
    FXPRESET_REVERB_ROOM = 120,
    FXPRESET_REVERB_BATHROOM = 130,
    FXPRESET_REVERB_LIVINGROOM = 140,
    FXPRESET_REVERB_STONEROOM = 150,
    FXPRESET_REVERB_AUDITORIUM = 160,
    FXPRESET_REVERB_CONCERTHALL = 170,
    FXPRESET_REVERB_CAVE = 180,
    FXPRESET_REVERB_ARENA = 190,
    FXPRESET_REVERB_HANGAR = 200,
    FXPRESET_REVERB_CARPETEDHALLWAY = 210,
    FXPRESET_REVERB_HALLWAY = 220,
    FXPRESET_REVERB_STONECORRIDOR = 230,
    FXPRESET_REVERB_ALLEY = 240,
    FXPRESET_REVERB_FOREST = 250,
    FXPRESET_REVERB_CITY = 260,
    FXPRESET_REVERB_MOUNTAINS = 270,
    FXPRESET_REVERB_QUARRY = 280,
    FXPRESET_REVERB_PLAIN = 290,
    FXPRESET_REVERB_PARKINGLOT = 300,
    FXPRESET_REVERB_SEWERPIPE = 310,
    FXPRESET_REVERB_UNDERWATER = 320,
};
// total size: 0x1
struct ExtendedFxPreset {};

enum FoldDownTarget {
    FOLDDOWNTARGET_MONO = 0,
    FOLDDOWNTARGET_STEREO = 1,
    FOLDDOWNTARGET_QUAD = 2,
    FOLDDOWNTARGET_5POINT1 = 3,
    FOLDDOWNTARGET_MAX = 4,
};

}

#endif
